
---
string frame_id
float32[3] offset

bool has_grasped_obj
float32[3] observed_manipulator_origin
float32[3] grasped_obj_origin
float32[3] grasped_obj_geometry
visualization_msgs/Marker grasped_obj_marker
